server:
  port: 7702

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

  client:
    serviceUrl:
      defaultZone: http://@eureka.user.name@:@eureka.user.password@@localhost:7700/eureka/

management:
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
spring:
  application:
    name: eureka-client-customer
  cloud:
    loadbalancer:
      retry:
        enabled: false
