server:
  port: 7704

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://@eureka.user.name@:@eureka.user.password@@localhost:7700/eureka/

spring:
  application:
    name: eureka-client-config-server
  cloud:
    loadbalancer:
      retry:
        enabled: false
  profiles:
    active: native
